[package]
name = "no-mans-sky"
version = "0.2.0"
authors = ["github.com/jerryshell/no-mans-sky"]
edition = "2021"

[dependencies]
anyhow = "1.0.52"
chrono = "0.4.19"
ctrlc = { version = "3.2.1", features = ["termination"] }
clap = { version = "3.0.10", features = ["derive"] }
